const { PrismaClient } = require('@prisma/client')
const prisma = new PrismaClient()
prisma.business.findMany({ select: { name: true, categoryId: true, categoryLegacy: true } })
  .then(r => console.log(JSON.stringify(r, null, 2)))
  .catch(console.error)
  .finally(() => prisma.$disconnect())
